// <auto-generated />
using System;
using Hospital.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Data.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20260703081752_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Data.Entities.FulfillmentEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FulfilledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FulfillmentEvent");
                });

            modelBuilder.Entity("Hospital.Data.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StockAmount")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId")
                        .IsUnique();

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchNumber = "BATCH-M12",
                            ExpirationDate = new DateTime(2028, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicationId = 1,
                            StockAmount = 5,
                            Supplier = "PharmaCorp Inc"
                        },
                        new
                        {
                            Id = 2,
                            BatchNumber = "BATCH-A99",
                            ExpirationDate = new DateTime(2027, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicationId = 2,
                            StockAmount = 3,
                            Supplier = "Global Meds Dist"
                        },
                        new
                        {
                            Id = 3,
                            BatchNumber = "BATCH-I44",
                            ExpirationDate = new DateTime(2029, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicationId = 3,
                            StockAmount = 8,
                            Supplier = "PharmaCorp Inc"
                        });
                });

            modelBuilder.Entity("Hospital.Data.Entities.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Medication");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "Toprol XL",
                            DosageForm = "Tablet",
                            GenericName = "Metoprolol",
                            Name = "Metoprolol Succinate",
                            Strength = "50mg",
                            UnitPrice = 0.75m
                        },
                        new
                        {
                            Id = 2,
                            BrandName = "Amoxil",
                            DosageForm = "Capsule",
                            GenericName = "Amoxicillin",
                            Name = "Amoxicillin Trihydrate",
                            Strength = "500mg",
                            UnitPrice = 0.40m
                        },
                        new
                        {
                            Id = 3,
                            BrandName = "Advil",
                            DosageForm = "Tablet",
                            GenericName = "Ibuprofen",
                            Name = "Ibuprofen",
                            Strength = "400mg",
                            UnitPrice = 0.15m
                        },
                        new
                        {
                            Id = 4,
                            BrandName = "Lipitor",
                            DosageForm = "Tablet",
                            GenericName = "Atorvastatin",
                            Name = "Lipitor",
                            Strength = "20mg",
                            UnitPrice = 1.25m
                        });
                });

            modelBuilder.Entity("Hospital.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Hospital.Data.Entities.OrderLines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("Hospital.Data.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Insurance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            Allergies = "Penicillin",
                            BloodType = "O-",
                            ContactNumber = "555-1234",
                            DateOfBirth = new DateTime(1815, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ada@example.com",
                            EmergencyContactName = "John Doe",
                            EmergencyContactNumber = "555-5678",
                            FirstName = "Ada",
                            Insurance = "Blue Cross",
                            LastName = "Lovelace"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave",
                            Allergies = "Shellfish",
                            BloodType = "A+",
                            ContactNumber = "555-9012",
                            DateOfBirth = new DateTime(1912, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alan@example.com",
                            EmergencyContactName = "Jane Smith",
                            EmergencyContactNumber = "555-3456",
                            FirstName = "Alan",
                            Insurance = "Cigna",
                            LastName = "Turing"
                        });
                });

            modelBuilder.Entity("Hospital.Data.Entities.InventoryItem", b =>
                {
                    b.HasOne("Hospital.Data.Entities.Medication", "Medication")
                        .WithOne("Inventory")
                        .HasForeignKey("Hospital.Data.Entities.InventoryItem", "MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("Hospital.Data.Entities.Order", b =>
                {
                    b.HasOne("Hospital.Data.Entities.Patient", "Patient")
                        .WithMany("Orders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital.Data.Entities.OrderLines", b =>
                {
                    b.HasOne("Hospital.Data.Entities.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.Data.Entities.Medication", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Hospital.Data.Entities.Order", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Hospital.Data.Entities.Patient", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
